In [4]:
def run_smart_grader_simple():
    
    name=input("Enter name:")
    roll=input("Enter roll number")
    
    marks = []

    print("Enter marks (out of 100) for 3 subjects:")
    for i in range(3):
        mark = int(input(f"Mark {i + 1}: "))
        if 0 <= mark <= 100:
            marks.append(mark)
    
    total= sum(marks)
    average = sum(marks) / len(marks) if marks else 0

    # Determine grade
    if average >= 90:
        grade, remark = "A", "Excellent"
    elif average >= 75:
        grade, remark = "B", "Very Good"
    elif average >= 60:
        grade, remark = "C", "Satisfactory"
    elif average >= 40:
        grade, remark = "D", "Pass"
    else:
        grade, remark = "F", "Needs Improvement"

    # Display result
    print("--- Result ---")
    print(name)
    print(roll)
    print(f"Average: {average:.2f}")
    print(f"Total: {sum(marks)}")
    print(f"Grade: {grade}")
    print(f"Remark: {remark}")
    print("------------")

run_smart_grader_simple()

Enter name: Advika
Enter roll number 4


Enter marks (out of 100) for 3 subjects:


Mark 1:  90
Mark 2:  89
Mark 3:  100


--- Result ---
Advika
4
Average: 93.00
Total: 279
Grade: A
Remark: Excellent
------------


In [6]:
type= input("Select out of: +, -, /, *, **, //:")
if type== '+':
    a=int(input("Enter first number:"))
    b=int(input("Enter second number:"))
    print (a+b)

elif type== '-':
    a=int(input("Enter first number:"))
    b=int(input("Enter second number:"))
    print (a-b)

elif type== '/':
    a=int(input("Enter first number:"))
    b=int(input("Enter second number:"))
    if b!=0:
        print (a/b)
    else:
        print("Denominator cannot be 0")

elif type== '*':
    a=int(input("Enter first number:"))
    b=int(input("Enter second number:"))
    print (a*b)

elif type== '**':
    a=int(input("Enter first number:"))
    b=int(input("Enter second number:"))
    print (a**b)

elif type== '//':
    a=int(input("Enter first number:"))
    b=int(input("Enter second number:"))
    if b!=0:
        print (a//b)
    else:
        print("Denominator cannot be zero.")

Select out of: +, -, /, *, **, //: //
Enter first number: 89
Enter second number: 0


Denominator cannot be zero.


In [12]:
def generate_salary_slip():
  
    print("--- Salary Slip Generator ---")

    employee_name = input("Enter Employee Name: ")
    basic_salary = float(input("Enter Basic Salary (monthly): "))
    if basic_salary <= 0:
        print("Basic salary cannot be negative. Please enter a positive value.")
    
    # 2. Define simple rates (in percentage)
    # These are illustrative rates for basic calculation
    HRA_RATE = 0.10  # 10% House Rent Allowance
    DA_RATE = 0.05   # 5% Dearness Allowance
    PF_RATE = 0.12   # 12% Provident Fund (Deduction)

    # 3. Calculations
    hra = basic_salary * HRA_RATE
    da = basic_salary * DA_RATE
    pf = basic_salary * PF_RATE

    # Gross Salary = Basic + HRA + DA (Total Earnings)
    gross_salary = basic_salary + hra + da

    # Net Salary = Gross Salary - PF (Final Takeaway)
    net_salary = gross_salary - pf

    # 4. Display Result (The Salary Slip)
    print("\n" + "="*40)
    print("            SALARY SLIP")
    print("="*40)
    print(f"Employee Name: {employee_name}")
    print(f"Basic Salary:  ₹ {basic_salary:,.2f}")
    print("-" * 40)
    
    # Earning Components
    print("Earnings:")
    print(f"  HRA (10%):   ₹ {hra:,.2f}")
    print(f"  DA (5%):     ₹ {da:,.2f}")
    print("-" * 40)
    print(f"GROSS SALARY:  ₹ {gross_salary:,.2f}")
    print("-" * 40)
    
    # Deduction Components
    print("Deductions:")
    print(f"  PF (12%):    ₹ {pf:,.2f}")
    print("-" * 40)
    
    # Final Net Pay
    print(f"NET PAYABLE:   ₹ {net_salary:,.2f}")
    print("="*40 + "\n")


# Run the function
if __name__ == "__main__":
    generate_salary_slip()

--- Salary Slip Generator ---


Enter Employee Name:  Advika
Enter Basic Salary (monthly):  72000



            SALARY SLIP
Employee Name: Advika
Basic Salary:  ₹ 72,000.00
----------------------------------------
Earnings:
  HRA (10%):   ₹ 7,200.00
  DA (5%):     ₹ 3,600.00
----------------------------------------
GROSS SALARY:  ₹ 82,800.00
----------------------------------------
Deductions:
  PF (12%):    ₹ 8,640.00
----------------------------------------
NET PAYABLE:   ₹ 74,160.00



In [12]:
def generate_salary_slip():
  
    print("--- Salary Slip Generator ---")

    employee_name = input("Enter Employee Name: ")
    basic_salary = float(input("Enter Basic Salary (monthly): "))
    if basic_salary <= 0:
        print("Basic salary cannot be negative. Please enter a positive value.")
    
    # 2. Define simple rates (in percentage)
    # These are illustrative rates for basic calculation
    HRA_RATE = 0.10  # 10% House Rent Allowance
    DA_RATE = 0.05   # 5% Dearness Allowance
    PF_RATE = 0.12   # 12% Provident Fund (Deduction)

    # 3. Calculations
    hra = basic_salary * HRA_RATE
    da = basic_salary * DA_RATE
    pf = basic_salary * PF_RATE

    # Gross Salary = Basic + HRA + DA (Total Earnings)
    gross_salary = basic_salary + hra + da

    # Net Salary = Gross Salary - PF (Final Takeaway)
    net_salary = gross_salary - pf

    # 4. Display Result (The Salary Slip)
    print("\n" + "="*40)
    print("            SALARY SLIP")
    print("="*40)
    print(f"Employee Name: {employee_name}")
    print(f"Basic Salary:  ₹ {basic_salary:,.2f}")
    print("-" * 40)
    
    # Earning Components
    print("Earnings:")
    print(f"  HRA (10%):   ₹ {hra:,.2f}")
    print(f"  DA (5%):     ₹ {da:,.2f}")
    print("-" * 40)
    print(f"GROSS SALARY:  ₹ {gross_salary:,.2f}")
    print("-" * 40)
    
    # Deduction Components
    print("Deductions:")
    print(f"  PF (12%):    ₹ {pf:,.2f}")
    print("-" * 40)
    
    # Final Net Pay
    print(f"NET PAYABLE:   ₹ {net_salary:,.2f}")
    print("="*40 + "\n")


# Run the function
if __name__ == "__main__":
    generate_salary_slip()

--- Salary Slip Generator ---


Enter Employee Name:  Advika
Enter Basic Salary (monthly):  72000



            SALARY SLIP
Employee Name: Advika
Basic Salary:  ₹ 72,000.00
----------------------------------------
Earnings:
  HRA (10%):   ₹ 7,200.00
  DA (5%):     ₹ 3,600.00
----------------------------------------
GROSS SALARY:  ₹ 82,800.00
----------------------------------------
Deductions:
  PF (12%):    ₹ 8,640.00
----------------------------------------
NET PAYABLE:   ₹ 74,160.00



In [16]:
def run_distance_converter():
    total_meters = int(input("Enter Total Distance in Meters (e.g., 5432): "))
    if total_meters <= 0:
        print("Distance must be a non-negative number.")

    # --- PART 1: Meters to Kilometers and Remaining Meters ---
    # 1 kilometer = 1000 meters.
    # We use integer division (//) to get the whole number of kilometers.
    kilometers = total_meters // 1000
    # We use the modulus operator (%) to get the remainder in meters.
    remaining_meters_km = total_meters % 1000

    print("Kilometer Conversion:")
    print(f"Total distance: {total_meters} meters")
    print(f"Is equal to:    {kilometers} km and {remaining_meters_km} meters")

    # --- PART 2: 400m Track Rounds ---
    # We use the same operators to find how many full 400m rounds fit into the distance.
    TRACK_LENGTH = 400
    track_rounds = total_meters // TRACK_LENGTH
    remaining_meters_track = total_meters % TRACK_LENGTH

    print("400m Track Rounds:")
    print(f"Track length:   {TRACK_LENGTH} meters")
    print(f"Total rounds:   {track_rounds} full rounds")
    print(f"Remaining distance: {remaining_meters_track} meters")


# Run the function
if __name__ == "__main__":
    run_distance_converter()

Enter Total Distance in Meters (e.g., 5432):  456789


Kilometer Conversion:
Total distance: 456789 meters
Is equal to:    456 km and 789 meters
400m Track Rounds:
Track length:   400 meters
Total rounds:   1141 full rounds
Remaining distance: 389 meters


In [1]:
def check_prime():
    """
    Checks if a given integer n is a prime number.
    Uses the while loop optimization (checks divisors up to sqrt(n)).
    """
    print("--- Prime Number Checker ---")
    n = int(input("Enter a whole number (n): "))
    if n <= 0:
        print("Please enter a non-negative whole number.")


    if n <= 1:
        # Numbers less than or equal to 1 are not prime
        is_prime = False
    else:
        is_prime = True
        i = 2
        # Check for factors from 2 up to the square root of n
        while i * i <= n:
            if n % i == 0:
                is_prime = False
                break
            i += 1

    print("-" * 40)
    print(f"Result for {n}:")
    print(f"{n} is prime" if is_prime else f"{n} is not prime")
    print("-" * 40)

if __name__ == "__main__":
    check_prime()

--- Prime Number Checker ---


Enter a whole number (n):  34


----------------------------------------
Result for 34:
34 is not prime
----------------------------------------


In [4]:
# Count characters, words, vowels; reverse word order.

s= input("Enter string:").lower().strip()
print (len(s))
VOWELS= "aeiou"
i=0
for string in s:
    if string in VOWELS:
        i+=VOWELS
        print (i)
reversed_s = s[::-1]
print(reversed_s)        


Enter string: Hello Mike


10


TypeError: unsupported operand type(s) for +=: 'int' and 'str'

In [8]:

user_input = input("Enter string: ")

# Prepare the string for processing (lowercase and remove punctuation for analysis)
# Keep the original input for the most accurate character length if needed
s = user_input.lower().strip()

## 1. Character Count
# Counts all characters after stripping leading/trailing whitespace
char_count = len(s) 
print(f"1. Total Characters (excluding leading/trailing spaces): {char_count}")

## 2. Word Count and Reverse Word Order
# Split the cleaned string into a list of words
words = s.split() 
word_count = len(words)
print(f"2. Total Words: {word_count}")

# Reverse word order using slice notation on the list of words
reversed_words = words[::-1]
print(f"3. Reverse Word Order: {reversed_words}")

## 3. Vowel Count (Fixed Logic)
VOWELS = "aeiou"
vowel_count = 0 # Use a descriptive variable name
for char in s:
    if char in VOWELS:
        vowel_count += 1 
        
print(f"4. Total Vowels: {vowel_count}")

Enter string:  Hello Mike


1. Total Characters (excluding leading/trailing spaces): 10
2. Total Words: 2
3. Reverse Word Order: ['mike', 'hello']
4. Total Vowels: 4


In [4]:
# Given list of marks: highest, lowest, average, sorted list, remove duplicates.
## Q6. Student Marks List Operations (Using Built-in Python)

ls = [56, 76, 76, 87, 89, 90, 94, 88, 100]

# 1. Highest Mark (Function)
highest = max(ls)
print(f"1. Highest Mark: {highest}")

# 2. Lowest Mark (Function)
lowest = min(ls)
print(f"2. Lowest Mark: {lowest}")

# 3. Average Mark (Functions)
# Average = Sum of all elements / Number of elements
average = sum(ls) / len(ls)
print(f"3. Average Mark: {average:.2f}")

# 4. Sorted List (Function)
# 'sorted()' returns a NEW sorted list, leaving 'ls' unchanged.
sorted_list = sorted(ls)
print(f"4. Sorted List: {sorted_list}")

# 5. Remove Duplicates (Set Conversion)
# The simplest Pythonic way: convert to a set (removes duplicates) and back to a list.
unique_list = list(set(ls))
print(f"5. Unique List: {unique_list}")

1. Highest Mark: 100
2. Lowest Mark: 56
3. Average Mark: 84.00
4. Sorted List: [56, 76, 76, 87, 88, 89, 90, 94, 100]
5. Unique List: [100, 76, 87, 56, 89, 90, 88, 94]


In [21]:
# Use tuple for month names and list for days; handle immutability with try-except.
i=2025
while i<2040:
    i+=4
    print(f"Leap years: {i}")
month= ("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
days= [31, 28, 31, 30, 31, 30, 31, 30, 31, 30, 31, 30]
days[1]= 29
print (days)
print (month)

Leap years: 2029
Leap years: 2033
Leap years: 2037
Leap years: 2041
[31, 29, 31, 30, 31, 30, 31, 30, 31, 30, 31, 30]
('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December')


In [22]:
# Addition: Z_1 + Z_2 = (a + c) + (b + d)i, Subtraction: Z_1 - Z_2 = (a - c) + (b - d)i
# The input numbers
c1 = (10, 5)   
c2 = (3, -2)

# --- Addition ---
# New Real part = 10 + 3
# New Imaginary part = 5 + (-2)
add_result = (c1[0] + c2[0], c1[1] + c2[1])
print(f"Addition Result (Tuple): {add_result}")
# Output: (13, 3)

# --- Subtraction ---
# New Real part = 10 - 3
# New Imaginary part = 5 - (-2)
sub_result = (c1[0] - c2[0], c1[1] - c2[1])
print(f"Subtraction Result (Tuple): {sub_result}")
# Output: (7, 7)

Addition Result (Tuple): (13, 3)
Subtraction Result (Tuple): (7, 7)


In [24]:
## Q9. Electricity Bill

def compute_electricity_bill(units):
    total_charge = 0
    surcharge_rate = 0.15  # 15% surcharge

    if units <= 100:
        rate = 5.00
        total_charge = units * rate
    elif units <= 300:
        # 100 units @ 5.00 + remaining units @ 7.50
        charge_slab1 = 100 * 5.00
        charge_slab2 = (units - 100) * 7.50
        total_charge = charge_slab1 + charge_slab2
    else: # units > 300
        # 100 units @ 5.00 + 200 units @ 7.50 + remaining units @ 10.00
        charge_slab1 = 100 * 5.00  # 500.00
        charge_slab2 = 200 * 7.50  # 1500.00
        charge_slab3 = (units - 300) * 10.00
        total_charge = charge_slab1 + charge_slab2 + charge_slab3

    # Apply Surcharge condition
    surcharge = 0
    if total_charge > 2000:
        surcharge = total_charge * surcharge_rate
        final_bill = total_charge + surcharge
    else:
        final_bill = total_charge

    print("\n--- Electricity Bill Summary ---")
    print(f"Units Consumed: {units}")
    print(f"Charge (before surcharge): ₹ {total_charge:,.2f}")
    print(f"Surcharge (15% if > ₹2000): ₹ {surcharge:,.2f}")
    print(f"**Total Bill Amount:** ₹ {final_bill:,.2f}")


try:
    units_consumed = int(input("Enter total units consumed: "))
    if units_consumed < 0:
        print("Units cannot be negative.")
    else:
        compute_electricity_bill(units_consumed)
except ValueError:
    print("Invalid input. Please enter a whole number for units.")

Enter total units consumed:  2100



--- Electricity Bill Summary ---
Units Consumed: 2100
Charge (before surcharge): ₹ 20,000.00
Surcharge (15% if > ₹2000): ₹ 3,000.00
**Total Bill Amount:** ₹ 23,000.00


In [3]:
# Check validity; classify (Equilateral/Isosceles/Scalene/Right-angled).

a= int(input("Enter side 1:"))
b= int(input("Enter side 2:"))
c= int(input("Enter side 3:"))

if a+b>c or b+c>a or a+c>b:
    print ("Triangle is valid")
else:
    print("Enter correct sides.")

if a==b or b==c or a==c:
    print ("Isosceles")

elif a==b==c:
    print ("Equilateral")

elif (a + b == c**2) or (a + c == b**2) or (b + c == a**2):
    print("It is a Right-Angled Triangle.")

else:
    print ("Scalene")

Enter side 1: 3
Enter side 2: 4
Enter side 3: 5


Triangle is valid
It is a Right-Angled Triangle.


In [16]:
# Admission eligibility- Physics, Chemistry, Maths: ≥60 each & overall ≥70
p= int(input("Enter Physics marks:"))
c= int(input("Enter Chemistry marks:"))
m= int(input("Enter Math marks:"))

if (p <= 60) or (c <= 60) or (m <= 60):
    print("Not eligible")
    
else:
    if p+c+m>=70:
        print ("Eligible")

Enter Physics marks: 56
Enter Chemistry marks: 78
Enter Math marks: 90


Not eligible


In [17]:
## Q12. Parking Charge Calculator (NO IMPORTS)

RATE_FIRST_HOUR = 10.00 # Charge for the first hour
RATE_AFTER_FIRST = 5.00 # Charge for every subsequent hour

try:
    hours_parked = float(input("Enter the total hours parked (e.g., 2.5): "))
    
    if hours_parked <= 0:
        print("Time must be greater than zero.")
    else:
        # 1. Calculate Billed Hours using Basic Python Logic (The trick!)
        
        # Start with the integer part of the hours
        integer_hours = int(hours_parked)
        
        # Check if there is any fractional part left
        if hours_parked > integer_hours:
            # If time is 2.1, integer_hours is 2. We add 1 to round up to 3.
            billed_hours = integer_hours + 1
        else:
            # If time is 2.0, integer_hours is 2. No rounding up needed.
            billed_hours = integer_hours
        
        
        charge_first_hour = 0
        charge_remaining = 0
        
        if billed_hours <= 1:
            # Case 1: 1 hour or less billed
            charge_first_hour = RATE_FIRST_HOUR
            total_charge = charge_first_hour
            remaining_billed_hours = 0
        else:
            # Case 2: More than 1 hour billed
            
            charge_first_hour = RATE_FIRST_HOUR
            remaining_billed_hours = billed_hours - 1
            charge_remaining = remaining_billed_hours * RATE_AFTER_FIRST
            
            total_charge = charge_first_hour + charge_remaining

        # --- Output ---
        print("\n" + "="*40)
        print(f"Time Parked: {hours_parked:.2f} hrs")
        print(f"Billed Hours: {billed_hours} hrs (Rounded Up)")
        print("-" * 40)
        
        print(f"1st Hour Charge:  ₹ {charge_first_hour:,.2f}")
        if remaining_billed_hours > 0:
             print(f"Remaining {remaining_billed_hours} hrs: ₹ {charge_remaining:,.2f}")
        
        print("-" * 40)
        print(f"**Total Charge:** ₹ {total_charge:,.2f}")
        print("="*40)

except ValueError:
    print("Error: Input must be a valid number.")

Enter the total hours parked (e.g., 2.5):  3



Time Parked: 3.00 hrs
Billed Hours: 3 hrs (Rounded Up)
----------------------------------------
1st Hour Charge:  ₹ 10.00
Remaining 2 hrs: ₹ 10.00
----------------------------------------
**Total Charge:** ₹ 20.00


In [18]:
N = 5 # Number of rows

print("--- Pattern using FOR-LOOP ---")
for i in range(1, N + 1): # Outer loop controls rows (i = 1 to 5)
    row_output = ""
    for j in range(1, i + 1): # Inner loop controls columns (j = 1 up to i)
        row_output += str(j) + " "
    print(row_output)

print("\n--- Pattern using WHILE-LOOP ---")
i = 1 
while i <= N:
    j = 1
    row_output = ""
    while j <= i:
        row_output += str(j) + " "
        j += 1
    print(row_output)
    i += 1

--- Pattern using FOR-LOOP ---
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 

--- Pattern using WHILE-LOOP ---
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [25]:
n= input("Choose among: Prime, Palindrome, and Factorial:")

if n=='Palindrome':
    user_input = input("Enter a word:").lower()
    reversed_input = user_input[::-1]
    if user_input==reversed_input:
        print("The word is a Palindrome.")
    else:
        print("The word is NOT a Palindrome.")

elif n== 'Factorial':
    num=int(input("Enter a number:"))
    factorial=1
    for i in range (num,1,-1):
        factorial= factorial*i
    print(factorial)

elif n=='Prime':
    def check_prime():
        print("--- Prime Number Checker ---")
        n = int(input("Enter a whole number (n): "))
        if n <= 0:
            print("Please enter a non-negative whole number.")


    if n <= 1:
        # Numbers less than or equal to 1 are not prime
        is_prime = False
    else:
        is_prime = True
        i = 2
        # Check for factors from 2 up to the square root of n
        while i * i <= n:
            if n % i == 0:
                is_prime = False
                break
            i += 1

    print("-" * 40)
    print(f"Result for {n}:")
    print(f"{n} is prime" if is_prime else f"{n} is not prime")
    print("-" * 40)
    
    if __name__ == "__main__":
        check_prime()

Choose among: Prime, Palindrome, and Factorial: Prime


TypeError: '<=' not supported between instances of 'str' and 'int'

In [26]:
## FIXED CODE: Menu-Driven Program

def check_prime():
    """Function to check for primality, takes input, returns result."""
    print("--- Prime Number Checker ---")
    
    # 1. FIX: Use 'num' instead of 'n' to avoid collision
    try:
        num = int(input("Enter a whole number: "))
    except ValueError:
        print("Invalid input. Please enter a whole number.")
        return # Exit function if input fails

    # 2. FIX: Move all logic INSIDE the function so it uses 'num'
    if num <= 1:
        is_prime = False
    else:
        is_prime = True
        i = 2
        # Check for factors up to the square root of num
        while i * i <= num:
            if num % i == 0:
                is_prime = False
                break
            i += 1
            
    # Print the result for the prime check
    print("-" * 40)
    print(f"Result for {num}:")
    print(f"{num} is prime" if is_prime else f"{num} is not prime")
    print("-" * 40)
    
# --- MAIN PROGRAM EXECUTION ---
n = input("Choose among: Prime, Palindrome, and Factorial:").lower() # Use .lower() for robust input

if n == 'palindrome':
    user_input = input("Enter a word:").lower()
    reversed_input = user_input[::-1]
    if user_input == reversed_input:
        print("The word is a Palindrome.")
    else:
        print("The word is NOT a Palindrome.")

elif n == 'factorial':
    num = int(input("Enter a number:"))
    factorial = 1
    # FIX: Corrected range to include 1 (stop at 0)
    for i in range(num, 0, -1):
        factorial = factorial * i
    print(factorial)

elif n == 'prime':
    # 3. FIX: Just call the function to run the whole logic
    check_prime()

else:
    print("Invalid choice.")

Choose among: Prime, Palindrome, and Factorial: Prime


--- Prime Number Checker ---


Enter a whole number:  34


----------------------------------------
Result for 34:
34 is not prime
----------------------------------------


In [28]:
## Q15. Digit Frequency Counter

try:
    number = int(input("Enter an integer: "))
except ValueError:
    print("Invalid input.")
    exit()

temp_num = abs(number) # Use the absolute value to handle negatives
frequencies = {}       # {digit: count}

if temp_num == 0:
    frequencies[0] = 1 # Handle the input 0

while temp_num > 0:
    # 1. Get the last digit
    digit = temp_num % 10  
    
    # 2. Add 1 to the count for that digit (or set it to 1 if first time)
    frequencies[digit] = frequencies.get(digit, 0) + 1
    
    # 3. Remove the last digit
    temp_num = temp_num // 10 

print(f"\nFrequencies in {number}:")
# Sort the output by digit for neatness
for digit in sorted(frequencies.keys()):
    print(f"Digit {digit}: {frequencies[digit]} times")

Enter an integer:  7777777777777



Frequencies in 7777777777777:
Digit 7: 13 times


In [29]:
## Q16. Fibonacci Series

try:
    n_terms = int(input("Enter the number of Fibonacci terms to generate: "))
except ValueError:
    print("Invalid input.")
    exit()

a, b = 0, 1       # Start terms
sum_even = 0
sum_odd = 0
count = 0

print("Fibonacci Series:")

while count < n_terms:
    print(a, end=" ")
    
    # Check if 'a' (the current term) is even or odd
    if a % 2 == 0:
        sum_even += a
    else:
        sum_odd += a

    # Update for the next iteration (a becomes the old b, b becomes the new sum)
    a, b = b, a + b
    count += 1

print(f"\n\nSum of Even terms: {sum_even}")
print(f"Sum of Odd terms: {sum_odd}")

Enter the number of Fibonacci terms to generate:  34


Fibonacci Series:
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 

Sum of Even terms: 4613732
Sum of Odd terms: 4613732


In [30]:
## Q18. Word Frequency Counter

import string             # Tool for getting punctuation list
from collections import Counter # FAST tool for counting things

FILE_NAME = "story.txt"

# --- STEP 0: Make sure the file exists (Create a quick dummy file) ---
# You'll need this part to run the code the first time
DUMMY_STORY = """
The fox runs fast. The dog runs slow. The dog and the fox are running.
"""
with open(FILE_NAME, 'w') as f:
    f.write(DUMMY_STORY)
print(f"File '{FILE_NAME}' created.")


def compute_word_frequency():
    try:
        # 1. READ
        with open(FILE_NAME, 'r') as file:
            text = file.read()

        # 2. CLEANING (The important stuff)
        text = text.lower() # Make everything lowercase

        # Remove punctuation (.,!?)
        translator = str.maketrans('', '', string.punctuation)
        clean_text = text.translate(translator)

        # Split into words (splits by spaces and removes empty strings)
        words = clean_text.split()
        
        # 3. COUNT
        word_counts = Counter(words)

        # 4. TOP 5
        top_5 = word_counts.most_common(5)

        print("-" * 50)
        print("--- Top 5 Word Frequencies ---")
        
        for rank, (word, count) in enumerate(top_5, 1):
            print(f"{rank}. '{word}': {count} times")

    except FileNotFoundError:
        print(f"Error: Couldn't find the file '{FILE_NAME}'.")

compute_word_frequency()

File 'story.txt' created.
--------------------------------------------------
--- Top 5 Word Frequencies ---
1. 'the': 4 times
2. 'fox': 2 times
3. 'runs': 2 times
4. 'dog': 2 times
5. 'fast': 1 times


In [32]:
## Q17. Student Records File

FILE_NAME = "student_records.txt"
MIN_PASS_MARK = 75

def write_records():
    """Writes N student records (Name, Roll, Marks) to the file."""
    try:
        n = int(input("Enter how many students to record: "))
        if n <= 0:
            print("Gotta have at least one student.")
            return

        # Open file in 'w' (write) mode. This overwrites the file every time.
        with open(FILE_NAME, 'w') as file:
            print("\n--- ENTERING RECORDS ---")
            for i in range(n):
                print(f"Record {i+1}:")
                name = input("  Name: ")
                roll = input("  Roll No: ")
                # Error handling to make sure marks is a number
                while True:
                    try:
                        marks = int(input("  Marks (0-100): "))
                        break
                    except ValueError:
                        print("    Marks gotta be a number, man.")
                
                # Write to file: Format is Name,Roll,Marks\n
                file.write(f"{name},{roll},{marks}\n")
        
        print(f"\nSaved {n} records to {FILE_NAME}.")

    except ValueError:
        print("Invalid input for student count.")

def read_and_filter_records():
    """Reads the file and prints students with marks >= 75."""
    print(f"\n--- ELIGIBLE STUDENTS (Marks >= {MIN_PASS_MARK}) ---")
    found_eligible = False
    
    try:
        # Open file in 'r' (read) mode
        with open(FILE_NAME, 'r') as file:
            
            # Loop through the file line by line
            for line in file:
                data = line.strip() # Removes the '\n' at the end
                if not data: continue # Skip if the line is empty

                try:
                    # Split the line by the comma: data -> [Name, Roll, Marks]
                    name, roll, marks_str = data.split(',')
                    marks = int(marks_str) # Convert marks back to integer
                    
                    # Check the condition
                    if marks >= MIN_PASS_MARK:
                        print(f"Name: {name:<10} | Roll No: {roll:<5} | Marks: {marks}")
                        found_eligible = True
                
                except Exception:
                     # This catches bad formatting or non-integer marks
                     print(f"Warning: Skipping bad record: {data}")
        
        if not found_eligible:
            print(f"No students found with marks above {MIN_PASS_MARK}.")
            
    except FileNotFoundError:
        print(f"Error: The file '{FILE_NAME}' isn't there. Run the writing function first.")

# Run both parts of the assignment
write_records()
read_and_filter_records()

Enter how many students to record:  3



--- ENTERING RECORDS ---
Record 1:


  Name:  A
  Roll No:  1
  Marks (0-100):  78


Record 2:


  Name:  B
  Roll No:  2
  Marks (0-100):  89


Record 3:


  Name:  C
  Roll No:  3
  Marks (0-100):  90



Saved 3 records to student_records.txt.

--- ELIGIBLE STUDENTS (Marks >= 75) ---
Name: A          | Roll No: 1     | Marks: 78
Name: B          | Roll No: 2     | Marks: 89
Name: C          | Roll No: 3     | Marks: 90


In [32]:
## Q17. Student Records File

FILE_NAME = "student_records.txt"
MIN_PASS_MARK = 75

def write_records():
    """Writes N student records (Name, Roll, Marks) to the file."""
    try:
        n = int(input("Enter how many students to record: "))
        if n <= 0:
            print("Gotta have at least one student.")
            return

        # Open file in 'w' (write) mode. This overwrites the file every time.
        with open(FILE_NAME, 'w') as file:
            print("\n--- ENTERING RECORDS ---")
            for i in range(n):
                print(f"Record {i+1}:")
                name = input("  Name: ")
                roll = input("  Roll No: ")
                # Error handling to make sure marks is a number
                while True:
                    try:
                        marks = int(input("  Marks (0-100): "))
                        break
                    except ValueError:
                        print("    Marks gotta be a number, man.")
                
                # Write to file: Format is Name,Roll,Marks\n
                file.write(f"{name},{roll},{marks}\n")
        
        print(f"\nSaved {n} records to {FILE_NAME}.")

    except ValueError:
        print("Invalid input for student count.")

def read_and_filter_records():
    """Reads the file and prints students with marks >= 75."""
    print(f"\n--- ELIGIBLE STUDENTS (Marks >= {MIN_PASS_MARK}) ---")
    found_eligible = False
    
    try:
        # Open file in 'r' (read) mode
        with open(FILE_NAME, 'r') as file:
            
            # Loop through the file line by line
            for line in file:
                data = line.strip() # Removes the '\n' at the end
                if not data: continue # Skip if the line is empty

                try:
                    # Split the line by the comma: data -> [Name, Roll, Marks]
                    name, roll, marks_str = data.split(',')
                    marks = int(marks_str) # Convert marks back to integer
                    
                    # Check the condition
                    if marks >= MIN_PASS_MARK:
                        print(f"Name: {name:<10} | Roll No: {roll:<5} | Marks: {marks}")
                        found_eligible = True
                
                except Exception:
                     # This catches bad formatting or non-integer marks
                     print(f"Warning: Skipping bad record: {data}")
        
        if not found_eligible:
            print(f"No students found with marks above {MIN_PASS_MARK}.")
            
    except FileNotFoundError:
        print(f"Error: The file '{FILE_NAME}' isn't there. Run the writing function first.")

# Run both parts of the assignment
write_records()
read_and_filter_records()

Enter how many students to record:  3



--- ENTERING RECORDS ---
Record 1:


  Name:  A
  Roll No:  1
  Marks (0-100):  78


Record 2:


  Name:  B
  Roll No:  2
  Marks (0-100):  89


Record 3:


  Name:  C
  Roll No:  3
  Marks (0-100):  90



Saved 3 records to student_records.txt.

--- ELIGIBLE STUDENTS (Marks >= 75) ---
Name: A          | Roll No: 1     | Marks: 78
Name: B          | Roll No: 2     | Marks: 89
Name: C          | Roll No: 3     | Marks: 90


In [33]:
## Q19. Array Statistics

import numpy as np

# Create a sample NumPy array
data_array = np.array([85, 12, 98, 55, 78, 98, 63, 15, 70, 42])
print(f"Original Array: {data_array}")
print("-" * 30)

# 1. Mean (Average)
print(f"Mean (Average):     {np.mean(data_array):.2f}")

# 2. Median (Middle value)
print(f"Median:             {np.median(data_array):.2f}")

# 3. Standard Deviation (Spread)
print(f"Std Dev:            {np.std(data_array):.2f}")

# 4. Maximum Value
print(f"Maximum Value:      {np.max(data_array)}")

# 5. Minimum Value
print(f"Minimum Value:      {np.min(data_array)}")

# 6. Index of Maximum Value (first occurrence)
print(f"Index of Max Value: {np.argmax(data_array)}")

Original Array: [85 12 98 55 78 98 63 15 70 42]
------------------------------
Mean (Average):     61.60
Median:             66.50
Std Dev:            29.32
Maximum Value:      98
Minimum Value:      12
Index of Max Value: 2


In [34]:
## Q20. Matrix Operations

import numpy as np

# Define two 2x3 matrices for addition and element-wise multiplication
matrix_A = np.array([[1, 2, 3], 
                     [4, 5, 6]])

matrix_B = np.array([[7, 8, 9], 
                     [10, 11, 12]])

# Define a third matrix (3x2) for the dot product
# (A is 2x3, C is 3x2, result is 2x2)
matrix_C = np.array([[1, 0], 
                     [0, 1], 
                     [1, 1]])

print("Matrix A:\n", matrix_A)
print("Matrix C:\n", matrix_C)
print("-" * 30)

# 1. Matrix Addition (Element-wise)
# Requires A and B to have the same dimensions (A + B)
addition_result = matrix_A + matrix_B
print("1. Matrix Addition (A + B):\n", addition_result)

# 2. Dot Product (True Matrix Multiplication)
# Uses np.dot() or the @ operator (A @ C)
dot_product_result = np.dot(matrix_A, matrix_C)
print("\n2. Dot Product (A * C):\n", dot_product_result)

# 3. Element-wise Multiplication (Hadamard Product)
# Uses the standard * operator (A * B)
element_wise_result = matrix_A * matrix_B
print("\n3. Element-wise Multiplication (A * B):\n", element_wise_result)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix C:
 [[1 0]
 [0 1]
 [1 1]]
------------------------------
1. Matrix Addition (A + B):
 [[ 8 10 12]
 [14 16 18]]

2. Dot Product (A * C):
 [[ 4  5]
 [10 11]]

3. Element-wise Multiplication (A * B):
 [[ 7 16 27]
 [40 55 72]]


In [35]:
## Q21. NumPy Advanced Indexing

import numpy as np

# 1. Generate 15 random scores (0 to 100)
# np.random.seed() ensures you get the same 'random' scores every time
np.random.seed(42) 
scores = np.random.randint(0, 101, 15)
print(f"Original 15 Scores:\n{scores}")
print("-" * 50)

# 2. Boolean Filter: Select scores >= 50
# Create the boolean mask
mask_pass = scores >= 50
print(f"Boolean Mask (scores >= 50):\n{mask_pass}")

# Use the mask to select and print the passing scores
passing_scores = scores[mask_pass]
print(f"\nPassing Scores (>= 50):\n{passing_scores}")
print("-" * 50)

# 3. Replace scores < 40 with 40
# Create a new mask for scores that are failing
mask_fail = scores < 40

# Use the mask to assign the value 40 to only those elements
scores[mask_fail] = 40

print("Final Modified Scores:")
print(f"Original scores < 40 are now 40:\n{scores}")

Original 15 Scores:
[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21]
--------------------------------------------------
Boolean Mask (scores >= 50):
[ True  True False  True  True False  True  True  True  True  True  True
 False False False]

Passing Scores (>= 50):
[51 92 71 60 82 86 74 74 87 99]
--------------------------------------------------
Final Modified Scores:
Original scores < 40 are now 40:
[51 92 40 71 60 40 82 86 74 74 87 99 40 40 40]


In [36]:
## Q22. Pandas Series - Sales Analysis

import pandas as pd

# Data: June to November sales
months = ['Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov']
current_sales = [25000, 28000, 31000, 35000, 33000, 40000]
previous_sales = [23000, 27000, 30000, 36000, 32000, 38000]

# Create two Series objects
sales_current = pd.Series(current_sales, index=months, name='Current Year')
sales_previous = pd.Series(previous_sales, index=months, name='Previous Year')

# Combine into a DataFrame to easily calculate the difference
sales_df = pd.DataFrame({'Current': sales_current, 'Previous': sales_previous})

# Calculate the difference and growth
sales_df['Difference'] = sales_df['Current'] - sales_df['Previous']
sales_df['Growth (%)'] = ((sales_df['Difference'] / sales_df['Previous']) * 100).round(2)

print("--- Sales Comparison ---")
print(sales_df)
print("\nMonths where Current Sales were HIGHER:")
# Use boolean indexing on the DataFrame
print(sales_df[sales_df['Difference'] > 0].index.tolist())

--- Sales Comparison ---
     Current  Previous  Difference  Growth (%)
Jun    25000     23000        2000        8.70
Jul    28000     27000        1000        3.70
Aug    31000     30000        1000        3.33
Sep    35000     36000       -1000       -2.78
Oct    33000     32000        1000        3.12
Nov    40000     38000        2000        5.26

Months where Current Sales were HIGHER:
['Jun', 'Jul', 'Aug', 'Oct', 'Nov']


In [37]:
## Q23. DataFrame - Student Result Table

import pandas as pd

data = {
    'Roll No': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Phy': [65, 88, 35, 75, 92],
    'Chem': [70, 95, 40, 80, 88],
    'Math': [60, 90, 25, 65, 95]
}
df = pd.DataFrame(data)

# 1. Add 'Total' Column
df['Total'] = df['Phy'] + df['Chem'] + df['Math']

# 2. Add 'Result' Column (Pass if all subjects >= 40)
# Use a lambda function with .apply() to check all columns in one row
df['Result'] = df.apply(
    lambda row: 'Pass' if all(row[s] >= 40 for s in ['Phy', 'Chem', 'Math']) else 'Fail', 
    axis=1 # axis=1 applies the function row-wise
)

print("--- Student Result Table ---")
print(df)

# 3. Filter Pass Students
passed_df = df[df['Result'] == 'Pass']
print("\n--- Passed Students ---")
print(passed_df)

# 4. Print Topper (using idxmax() to get the index of the max total)
topper = df.loc[df['Total'].idxmax()]
print("\n--- Class Topper ---")
print(f"Name: {topper['Name']}, Total: {topper['Total']}")

--- Student Result Table ---
   Roll No     Name  Phy  Chem  Math  Total Result
0      101    Alice   65    70    60    195   Pass
1      102      Bob   88    95    90    273   Pass
2      103  Charlie   35    40    25    100   Fail
3      104    David   75    80    65    220   Pass
4      105      Eve   92    88    95    275   Pass

--- Passed Students ---
   Roll No   Name  Phy  Chem  Math  Total Result
0      101  Alice   65    70    60    195   Pass
1      102    Bob   88    95    90    273   Pass
3      104  David   75    80    65    220   Pass
4      105    Eve   92    88    95    275   Pass

--- Class Topper ---
Name: Eve, Total: 275


In [38]:
## Q24. CSV Handling with Pandas

import pandas as pd

# Create a DUMMY CSV file content for testing
csv_data = """EmployeeID,Name,Department,Salary,Experience_Years
101,Alice,HR,60000,3
102,Bob,IT,95000,6
103,Charlie,HR,75000,8
104,David,Sales,80000,4
105,Eve,IT,110000,10
106,Frank,Sales,70000,2
"""
with open('employees.csv', 'w') as f:
    f.write(csv_data)


# 1. Read employees.csv
df = pd.read_csv('employees.csv')

# 2. Group by Department and compute Average Salary
avg_salary = df.groupby('Department')['Salary'].mean().reset_index()
print("--- Average Salary by Department ---")
print(avg_salary)

# 3. Filter employees with Experience > 5 years
MIN_EXP = 5
filtered_exp_df = df[df['Experience_Years'] > MIN_EXP]

print(f"\n--- Employees with Experience > {MIN_EXP} Years ---")
print(filtered_exp_df)

--- Average Salary by Department ---
  Department    Salary
0         HR   67500.0
1         IT  102500.0
2      Sales   75000.0

--- Employees with Experience > 5 Years ---
   EmployeeID     Name Department  Salary  Experience_Years
1         102      Bob         IT   95000                 6
2         103  Charlie         HR   75000                 8
4         105      Eve         IT  110000                10
